spring.application.name=banking-web

spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=NewPassword123!
spring.jpa.hibernate.ddl-auto=update

jwt.secret=ReplaceThisWithAStrongLongSecretKeyAtLeast32Chars
jwt.expirationMs=3600000
